### ISSUE TITLE
download the code find the bug

### ISSUE THREAD

**Issue by zhqpower** [Refloow/Steam-Card-Bot-PRO#40]
An error occurred while getting bot Gems inventory: Error: read ECONNRESET

**Comment by zhqpower** [comment]
![image](https://user-images.githubusercontent.com/8142420/153113378-e964fce4-f4b5-4027-8d07-60214480c668.png)

**Comment by Refloow** [comment]
> An error occurred while getting bot Gems inventory: Error: read ECONNRESET

Did the error crash the application or it continued working fine?
I would like to see console logs.

"ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. This is most probably due to one or more steam protocol errors. But there is nothing i can do about it, it happens sometimes when there is poor connection.
